export const DESTINATIONS = [
  { name: "Salvador", slug: "salvador" },
  { name: "Rio de Janeiro", slug: "rio-de-janeiro" },
  { name: "Barcelona", slug: "barcelona" },
  { name: "Gramado", slug: "gramado" },
  { name: "Moscow", slug: "moscow" },
  { name: "Amsterdam", slug: "amsterdam" },
  { name: "Buenos Aires", slug: "buenos-aires" },
  { name: "Tokyo", slug: "tokyo" },
  { name: "São Paulo", slug: "sao-paulo" },
  { name: "Madrid", slug: "madrid" },
  { name: "London", slug: "london" },
  { name: "Cairo", slug: "cairo" },
  { name: "Hong Kong", slug: "hong-kong" },
  { name: "Porto Alegre", slug: "porto-alegre" },
  { name: "San Francisco", slug: "san-francisco" },
  { name: "Paris", slug: "paris" },
  { name: "Vancouver", slug: "vancouver" },
  { name: "Dubai", slug: "dubai" },
  { name: "Bangkok", slug: "bangkok" },
  { name: "Los Angeles", slug: "los-angeles" },
  { name: "Cape Town", slug: "cape-town" },
  { name: "Fortaleza", slug: "fortaleza" },
  { name: "Sydney", slug: "sydney" },
  { name: "New York", slug: "new-york" },
  { name: "Istanbul", slug: "istanbul" },
  { name: "Rome", slug: "rome" },
  { name: "Fernando de Noronha", slug: "fernando-de-noronha" },
  { name: "Lisbon", slug: "lisbon" },
  { name: "Seoul", slug: "seoul" },
  { name: "Singapore", slug: "singapore" },
];
